drchrono_prep/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'drchrono_prep.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^schedule/', include('schedule.urls', namespace='schedule')),
    url(r'^forms/', include('forms.urls', namespace='forms')),
    url(r'^', include('main.urls', namespace='main')),
)

forms/urls.py
from django.conf.urls import patterns, url
from forms import views

urlpatterns = patterns('',
                       url(r'^$', views.index, name='index'),
                       url(r'^newuser/$', views.new_user, name='new_user'),
                       url(r'^newuser/create/$', views.create_user, name='create_user'),
                       url(r'^login/$', views.login_view, name='login'),
                       url(r'^logout/$', views.logout_view, name='logout'),
                       url(r'^newform/$', views.new_form, name='new_form'),
                       url(r'^newform/create/$', views.create_form, name='create_form'),
                       url(r'^(?P<form_id>\d+)/$', views.form, name='form'),
                       url(r'^(?P<form_id>\d+)/addelement/$', views.add_element, name='add_element'),
                       url(r'^(?P<form_id>\d+)/share', views.share_form, name='share_form'),
                       url(r'^view/(?P<form_id>\d+)/$', views.view_form, name='view_form'),
)

main/urls.py
from django.conf.urls import patterns, url
from main import views

urlpatterns = patterns('',
                       url(r'^$', views.index, name='index'),
                       url(r'^login', views.login_view, name='login'),
                       url(r'^logout', views.logout_view, name='logout'),
                       url(r'^user/', views.user_info, name='user'),
                       )

forms/models.py
from django.contrib.auth.models import User
from django.db import models

class Form(models.Model):
    user = models.ForeignKey(User)
    name = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return self.name


class Element(models.Model):
    form = models.ForeignKey(Form)
    ELEMENT_CHOICES = (
        ('BO', 'Boolean'),
        ('IN', 'Integer'),
    )
    type = models.CharField(max_length=20, choices=ELEMENT_CHOICES)
    name = models.CharField(max_length=150)


    def __str__(self):
        return self.name

forms/admin.py
from django.contrib import admin

# Register your models here.
from forms.models import Form, Element
admin.site.register(Form)
admin.site.register(Element)

forms/views.py
from django.contrib.auth import authenticate, logout, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core import mail
from django.core.mail import send_mail
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404

from forms.models import Form


@login_required
def index(request):
    user = request.user
    forms = user.form_set.all()
    return render(request, 'forms/index.html', {'request': request, 'forms': forms, })


def new_user(request):
    return render(request, 'forms/newuser.html', None)


def create_user(request):
    email = request.POST['email']
    username = request.POST['username']
    password = request.POST['password']
    user = User.objects.create_user(username, email, password)
    user.save()
    return HttpResponseRedirect(reverse('forms:index'))


def login_view(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    if user is not None:
        if user.is_active:
            login(request, user)
            return HttpResponseRedirect(reverse('forms:user', args=(user.id,)))
    else:
        return HttpResponseRedirect(reverse('forms:index'))


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('forms:index'))


@login_required
def new_form(request):
    user = request.user
    return render(request, 'forms/newform.html', {'request': request, 'user': user, })


@login_required
def create_form(request):
    user = request.user
    form = user.form_set.create(name=request.POST['name'], description=request.POST['description'])
    form.save()
    return HttpResponseRedirect(reverse('forms:form', args=(form.id,)))


@login_required
def form(request, form_id):
    user = request.user
    form = Form.objects.filter(user=user, pk=form_id)[0]
    elements = form.element_set.all()
    return render(request, 'forms/form.html', {'request': request, 'user': user, 'form': form, 'elements': elements})


@login_required
def add_element(request, form_id):
    user = request.user
    form = Form.objects.filter(user=user, pk=form_id)[0]
    element = form.element_set.create(name=request.POST['name'], type=request.POST['type'])
    element.save()
    return HttpResponseRedirect(reverse('forms:form', args=(form.id,)))


def view_form(request, form_id):
    form = get_object_or_404(Form, pk=form_id)
    elements = form.element_set.all()
    return render(request, 'forms/view_form.html', {'request': request, 'form': form, 'elements': elements, })


@login_required
def share_form(request, form_id):
    user = request.user
    link = "http://" + request.get_host() + reverse('forms:view_form', args=(form_id,))
    connection = mail.get_connection()
    send_mail('Form Designer: Shared form from ' + user.username, request.POST['message'] + '\n\n' + link, user.email,
              [request.POST['to_email']], connection=connection)
    connection.close()
    return HttpResponseRedirect(reverse('forms:form', args=(form_id,)))

forms/templates/forms/form.html
{% extends 'main/base.html' %}

{% block title %}Form{% endblock %}
{% block forms_class %}active{% endblock %}

{% block content %}
    <br/>
    <div class="card">
        <div class="container-fluid">
            <h2>
                <small style="font-size: 34px; text-decoration: underline">{{ form.name }}</small>
            </h2>

            <h3>
                <small style="font-size:26px">{{ form.description }}</small>
            </h3>
            <hr/>
            {% if elements %}
                {% for element in elements %}
                    {% if element.type == "Integer" %}
                        <p>{{ element.name }}</p>
                        <input type="text" maxlength="10" size="11" placeholder="Integer" class="form-control"/>
                    {% elif element.type == "Boolean" %}
                        <span>{{ element.name }}</span><input type="checkbox" class="form-control"/>
                    {% endif %}
                    <hr/>
                {% endfor %}
            {% else %}
                <p>There are no elements to show yet.</p>
            {% endif %}
        </div>
    </div>
    <h4>Add a new element:</h4>
    <hr/>
    <div class="container-fluid card">
        <form action="{% url 'forms:add_element' form.id %}" method="post" class="form-group">
            {% csrf_token %}
            <br/>
            <input type="text" name="name" placeholder="Element name" class="form-control"/>
            <br/>
            <select name="type" class="selectpicker" data-style="form-control" data-menu-style="">
                <option value="" disabled selected>Type</option>
                <option value="Integer">Integer</option>
                <option value="Boolean">Boolean</option>
            </select>
            <br/>
            <br/>
            <input type="submit" value="Add form element" class="form-control"/>
        </form>
    </div>
    <h4>Share form:</h4>
    <hr>
    <div class="container-fluid card">
        <form action="{% url 'forms:share_form' form.id %}" method="post" class="form-group">
            {% csrf_token %}
            <br/>
            <input type="text" name="to_email" placeholder="Recipient's email address" class="form-control"/>
            <br/>
            <textarea class="form-control" name="message" placeholder="Message (optional)"></textarea>
            <br/>
            <input type="submit" value="Share form" class="form-control"/>
        </form>
    </div>
    <h4><a href="{% url 'forms:index' %}">Return to the home page.</a></h4>
    <br/>
    <br/>
{% endblock %}

forms/templates/forms/index.html
{% extends 'main/base.html' %}

{% block title %}Forms Home{% endblock %}
{% block forms_class %}active{% endblock %}

{% block content %}
    <h1>Form Designer</h1>
    <h3>This is the form designer area! Here you can create and share custom input forms for whatever task you need to
        accomplish.</h3>
    <br/>
    <h2>Current Forms:</h2>
    {% if forms %}
        <ul>
            {% for form in forms %}
                <li><a href="{% url 'forms:form' form.id %}" style="font-size:18px">{{ form.name }}</a></li>
                <br/>
            {% endfor %}
        </ul>
        <a href="{% url 'forms:new_form' %}">Create a new form</a>
    {% else %}
        <p>There are no forms to show yet! <a href="{% url 'forms:new_form' %}">Create your first form here!</a>
        </p>
    {% endif %}
    <br/>
    <br/>
    <br/>
{% endblock %}

forms/templates/forms/main_template.html
{% load staticfiles %}
<html>
<head>

    <link href="{% static 'forms/bootstrap3/css/bootstrap.css' %}" rel="stylesheet"/>
    <link href="{% static 'forms/bootstrap3/css/boostrap-theme.css' %}" rel="stylesheet"/>
    <link rel="stylesheet" href="{% static 'forms/assets/css/gsdk.css' %}"/>
    <link rel="stylesheet" href="{% static 'forms/assets/css/examples.css' %}">
    <link rel="stylesheet" href="{% static 'forms/assets/css/demo.css' %}">
    <link rel="stylesheet" href="{% static 'forms/main.css' %}">
</head>

<body>
<nav class="navbar navbar-ct-red" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            {% if request.user.is_authenticated %}
            <a class="navbar-brand" href="{% url 'forms:user' user.id %}">Form Designer</a>
            {% else %}
            <a class="navbar-brand" href="{% url 'forms:index' %}">Form Designer</a>
            {% endif %}
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1">

                <span class="sr-only">Toggle navigation</span>

                <span class="icon-bar"></span>

                <span class="icon-bar"></span>

                <span class="icon-bar"></span>

            </button>
        </div>


        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <div class="container-fluid">
                <ul class="nav navbar-nav">
                    <li class="active">{% block home_link %}<a href="{% url 'forms:index' %}">Home</a>{% endblock %}
                    </li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    <li>
                        {% if request.user.is_authenticated %}
                            <a class="btn btn-default" href="{% url 'forms:logout' %}">Logout</a>
                        {% endif %}
                    </li>
                </ul>
            </div>

        </div>
    </div>
</nav>
<div class="main">
    <div class="container" role="main">
        <div class="content">
            <div class="card col-md-6">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>
</div>
</body>

<script src="{% static 'forms/assets/js/jquery-1.10.2.js' %}" type="text/javascript"></script>
<script src="{% static 'forms/assets/js/jquery-ui-1.10.4.custom.min.js' %}" type="text/javascript"></script>

<script src="{% static 'forms/bootstrap3/js/bootstrap.js' %}" type="text/javascript"></script>

<!--  Plugins -->
<script src="{% static 'forms/assets/js/gsdk-checkbox.js' %}"></script>
<script src="{% static 'forms/assets/js/gsdk-morphing.js' %}"></script>
<script src="{% static 'forms/assets/js/gsdk-radio.js' %}"></script>
<script src="{% static 'forms/assets/js/gsdk-bootstrapswitch.js' %}"></script>
<script src="{% static 'forms/assets/js/bootstrap-select.js' %}"></script>
<script src="
{% static 'forms/assets/js/bootstrap-datepicker.js' %}"></script>
<script src="{% static 'forms/assets/js/chartist.min.js' %}"></script>
<script src="
{% static 'forms/assets/js/jquery.tagsinput.js' %}"></script>

<script src="{% static 'forms/assets/js/get-shit-done.js' %}"></script>

</html>

forms/templates/forms/newform.html
{% extends 'main/base.html' %}

{% block title %}New Form{% endblock %}
{% block forms_class %}active{% endblock %}

{% block content %}
    <h1>Form Details</h1>
    <form action="{% url 'forms:create_form' %}" method="post" class="form-group">
        {% csrf_token %}
        <input type="text" placeholder="Form name" name="name" class="form-control"/>
        <br/>
        <textarea placeholder="Description" name="description" class="form-control"></textarea>
        <br/>
        <input type="submit" value="Create form" class="form-control"/>
    </form>
{% endblock %}

forms/templates/forms/newuser.html
{% extends 'main/base.html' %}

{% block title %}New user{% endblock %}
{% block forms_class %}active{% endblock %}

{% block content %}
    <h1>New User</h1>
    <form action="{% url 'forms:create_user' %}" method="post">
        {% csrf_token %}
        <input type="text" placeholder="Username" class="form-control" name="username"/>
        <br/>
        <input type="email" placeholder="Email" class="form-control" name="email"/>
        <br/>
        <input type="password" placeholder="Password" class="form-control" name="password"/>
        <br/>
        <input type="submit" value="Create Account" class="form-control btn btn-primary"/>
    </form>
{% endblock %}

forms/templates/forms/view_form.html
{% extends 'main/base.html' %}
{% block title %}{{ form.name }}{% endblock %}
{% block forms_class %}active{% endblock %}

{% block content %}
    <br/>
    <div class="card">
        <div class="container-fluid">
            <h2>
                <small style="font-size: 34px; text-decoration: underline">{{ form.name }}</small>
            </h2>

            <h3>
                <small style="font-size:26px">{{ form.description }}</small>
            </h3>
            <hr/>
            {% if elements %}
                {% for element in elements %}
                    {% if element.type == "Integer" %}
                        <p>{{ element.name }}</p>
                        <input type="text" maxlength="10" size="11" placeholder="Integer" class="form-control"/>
                    {% elif element.type == "Boolean" %}
                        <span>{{ element.name }}</span><input type="checkbox" class="form-control"/>
                    {% endif %}
                    <hr/>
                {% endfor %}
            {% else %}
                <p>There are no elements to show yet.</p>
            {% endif %}
        </div>
    </div>
{% endblock %}