drchrono_prep/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'drchrono_prep.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^schedule/', include('schedule.urls', namespace='schedule')),
    url(r'^forms/', include('forms.urls', namespace='forms')),
    url(r'^', include('main.urls', namespace='main')),
)

forms/urls.py
from django.conf.urls import patterns, url
from forms import views

urlpatterns = patterns('',
                       url(r'^$', views.index, name='index'),
                       url(r'^newuser/$', views.new_user, name='new_user'),
                       url(r'^newuser/create/$', views.create_user, name='create_user'),
                       url(r'^login/$', views.login_view, name='login'),
                       url(r'^logout/$', views.logout_view, name='logout'),
                       url(r'^newform/$', views.new_form, name='new_form'),
                       url(r'^newform/create/$', views.create_form, name='create_form'),
                       url(r'^(?P<form_id>\d+)/$', views.form, name='form'),
                       url(r'^(?P<form_id>\d+)/addelement/$', views.add_element, name='add_element'),
                       url(r'^(?P<form_id>\d+)/share', views.share_form, name='share_form'),
                       url(r'^view/(?P<form_id>\d+)/$', views.view_form, name='view_form'),
)

main/urls.py
from django.conf.urls import patterns, url
from main import views

urlpatterns = patterns('',
                       url(r'^$', views.index, name='index'),
                       url(r'^login', views.login_view, name='login'),
                       url(r'^logout', views.logout_view, name='logout'),
                       url(r'^user/', views.user_info, name='user'),
                       )

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render


# Create your views here.
def index(request):
    return render(request, 'main/index.html', None)


def create_user(request):
    email = request.POST['email']
    username = request.POST['username']
    password = request.POST['password']
    user = User.objects.create_user(username, email, password)
    user.save()
    return HttpResponseRedirect(reverse('forms:index'))


def login_view(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    if user is not None:
        if user.is_active:
            login(request, user)
            return HttpResponseRedirect(reverse('main:user'))
    else:
        return HttpResponseRedirect(reverse('main:index'))


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('main:index'))


@login_required
def user_info(request):
    user = request.user
    return render(request, 'main/user.html', {'request': request, 'user': user, })

main/templates/main/base.html
{% load staticfiles %}
<html>
<head>

    <link href="{% static 'forms/bootstrap3/css/bootstrap.css' %}" rel="stylesheet"/>
    <link href="{% static 'forms/bootstrap3/css/boostrap-theme.css' %}" rel="stylesheet"/>
    <link rel="stylesheet" href="{% static 'forms/assets/css/gsdk.css' %}"/>
    <link rel="stylesheet" href="{% static 'forms/assets/css/examples.css' %}">
    <link rel="stylesheet" href="{% static 'forms/assets/css/demo.css' %}">
    <link rel="stylesheet" href="{% static 'schedule/main.css' %}">

    <title>drchrono prep - {% block title %}{% endblock %}</title>
</head>

<body>
<nav class="navbar navbar-ct-red" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'main:user' %}">drchrono prepwork</a>
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1">

                <span class="sr-only">Toggle navigation</span>

                <span class="icon-bar"></span>

                <span class="icon-bar"></span>

                <span class="icon-bar"></span>

            </button>
        </div>


        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <div class="container-fluid">
                <ul class="nav navbar-nav">
                    <li class="{% block home_class %}{% endblock %}">{% block home_link %}<a href="{% url 'main:user' %}">Home</a>{% endblock %}
                    </li>
                    <li class="{% block schedule_class %}{% endblock %}"><a href="{% url 'schedule:index' %}">Schedules</a></li>
                    <li class="{% block forms_class %}{% endblock %}"><a href="{% url 'forms:index' %}">Forms</a></li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    <li>
                        {% if request.user.is_authenticated %}
                            <a class="btn btn-default" href="{% url 'main:logout' %}">Logout</a>
                        {% endif %}
                    </li>
                </ul>
            </div>

        </div>
    </div>
</nav>
<div class="main">
    <div class="container" role="main">
        <div class="content">
            <div class="card col-md-12" style="background-color: white">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>
</div>
</body>

<script src="{% static 'forms/assets/js/jquery-1.10.2.js' %}" type="text/javascript"></script>
<script src="{% static 'forms/assets/js/jquery-ui-1.10.4.custom.min.js' %}" type="text/javascript"></script>

<script src="{% static 'forms/bootstrap3/js/bootstrap.js' %}" type="text/javascript"></script>

<!--  Plugins -->
<script src="{% static 'forms/assets/js/gsdk-checkbox.js' %}"></script>
<script src="{% static 'forms/assets/js/gsdk-morphing.js' %}"></script>
<script src="{% static 'forms/assets/js/gsdk-radio.js' %}"></script>
<script src="{% static 'forms/assets/js/gsdk-bootstrapswitch.js' %}"></script>
<script src="{% static 'forms/assets/js/bootstrap-select.js' %}"></script>
<script src="
{% static 'forms/assets/js/bootstrap-datepicker.js' %}"></script>
<script src="{% static 'forms/assets/js/chartist.min.js' %}"></script>
<script src="{% static 'forms/assets/js/jquery.tagsinput.js' %}"></script>

<script src="{% static 'forms/assets/js/get-shit-done.js' %}"></script>

</html>

main/templates/main/index.html
{% extends 'main/base.html' %}

{% block title %}Home{% endblock %}
{% block home_class %}active{% endblock %}

{% block content %}
    <h1>Login</h1>
    <form action="{% url 'main:login' %}" method="post">
        {% csrf_token %}
        <input type="text" placeholder="Username" name="username" class="form-control"/>
        <br/>
        <input type="password" placeholder="Password" name="password" class="form-control"/>
        <br/>
        <input type="submit" value="Login" class="btn btn-primary" class="form-control"/>
    </form>
    <h1>Create a new account</h1>
    <form action="{% url 'forms:create_user' %}" method="post">
        {% csrf_token %}
        <input type="text" placeholder="Username" class="form-control" name="username"/>
        <br/>
        <input type="email" placeholder="Email" class="form-control" name="email"/>
        <br/>
        <input type="password" placeholder="Password" class="form-control" name="password"/>
        <br/>
        <input type="submit" value="Create Account" class="form-control btn btn-primary"/>
    </form>

    <br/>
    <br/>
{% endblock %}

main/templates/main/main_template.html
{% load staticfiles %}
<html>
<head>

    <link href="{% static 'forms/bootstrap3/css/bootstrap.css' %}" rel="stylesheet"/>
    <link href="{% static 'forms/bootstrap3/css/boostrap-theme.css' %}" rel="stylesheet"/>
    <link rel="stylesheet" href="{% static 'forms/assets/css/gsdk.css' %}"/>
    <link rel="stylesheet" href="{% static 'forms/assets/css/examples.css' %}">
    <link rel="stylesheet" href="{% static 'forms/assets/css/demo.css' %}">
    <link rel="stylesheet" href="{% static 'schedule/main.css' %}">
</head>

<body>
<nav class="navbar navbar-ct-red" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'main:user' %}">drchrono prepwork</a>
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1">

                <span class="sr-only">Toggle navigation</span>

                <span class="icon-bar"></span>

                <span class="icon-bar"></span>

                <span class="icon-bar"></span>

            </button>
        </div>


        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <div class="container-fluid">
                <ul class="nav navbar-nav">
                    <li class="active">{% block home_link %}<a href="{% url 'main:user' %}">Home</a>{% endblock %}
                    </li>
                    <li><a href="{% url 'schedule:index' %}">Schedules</a></li>
                    <li><a href="{% url 'forms:index' %}">Forms</a></li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    <li>
                        {% if request.user.is_authenticated %}
                            <a class="btn btn-default" href="{% url 'main:logout' %}">Logout</a>
                        {% endif %}
                    </li>
                </ul>
            </div>

        </div>
    </div>
</nav>
<div class="main">
    <div class="container" role="main">
        <div class="content">
            <div class="card col-md-12" style="background-color: white">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>
</div>
</body>

<script src="{% static 'forms/assets/js/jquery-1.10.2.js' %}" type="text/javascript"></script>
<script src="{% static 'forms/assets/js/jquery-ui-1.10.4.custom.min.js' %}" type="text/javascript"></script>

<script src="{% static 'forms/bootstrap3/js/bootstrap.js' %}" type="text/javascript"></script>

<!--  Plugins -->
<script src="{% static 'forms/assets/js/gsdk-checkbox.js' %}"></script>
<script src="{% static 'forms/assets/js/gsdk-morphing.js' %}"></script>
<script src="{% static 'forms/assets/js/gsdk-radio.js' %}"></script>
<script src="{% static 'forms/assets/js/gsdk-bootstrapswitch.js' %}"></script>
<script src="{% static 'forms/assets/js/bootstrap-select.js' %}"></script>
<script src="
{% static 'forms/assets/js/bootstrap-datepicker.js' %}"></script>
<script src="{% static 'forms/assets/js/chartist.min.js' %}"></script>
<script src="{% static 'forms/assets/js/jquery.tagsinput.js' %}"></script>

<script src="{% static 'forms/assets/js/get-shit-done.js' %}"></script>

</html>

main/templates/main/user.html
{% extends 'main/base.html' %}

{% block title %}{{ user.username }}{% endblock %}
{% block home_class %}active{% endblock %}

{% block content %}
    <h1>Hello, {{ user.username }}!</h1>
    <h3>While you're here, take a look around! Go <a href="{% url 'forms:index' %}">design some forms</a> or check out
        our <a href="{% url 'schedule:index' %}">immunization
            schedule area!</a></h3>
{% endblock %}