drchrono_prep/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'drchrono_prep.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^schedule/', include('schedule.urls', namespace='schedule')),
    url(r'^forms/', include('forms.urls', namespace='forms')),
    url(r'^', include('main.urls', namespace='main')),
)

main/urls.py
from django.conf.urls import patterns, url
from main import views

urlpatterns = patterns('',
                       url(r'^$', views.index, name='index'),
                       url(r'^login', views.login_view, name='login'),
                       url(r'^logout', views.logout_view, name='logout'),
                       url(r'^user/', views.user_info, name='user'),
                       )

schedule/urls.py
from django.conf.urls import patterns, url
from schedule import views

urlpatterns = patterns('',
                       url(r'^(?P<family_id>\d+)/(?P<member_id>\d+)/chart/$', views.chart, name='chart'),
                       url(r'^$', views.index, name='index'),
                       url(r'^(?P<family_id>\d+)/(?P<member_id>\d+)/chart/update', views.update_schedule,
                           name="update"),
                       url(r'^newfamily/$', views.new_family_view, name='new_family'),
                       url(r'^newfamily/add/', views.add_family, name='add_family'),
                       url(r'^(?P<family_id>\d+)/$', views.family_view, name='family'),
                       url(r'^(?P<family_id>\d+)/add', views.add_member, name='add_member')

                       )

schedule/models.py
from django.db import models
from django.contrib.auth.models import User


class PatientFamily(models.Model):
    user = models.ForeignKey(User)
    last_name = models.CharField(max_length=30)

    def __str__(self):
        return self.last_name


class Patient(models.Model):
    family = models.ForeignKey(PatientFamily)
    last_name = models.CharField(max_length=30)
    first_name = models.CharField(max_length=20)

    def __str__(self):
        return f"{self.last_name}, {self.first_name}"


class Schedule(models.Model):
    patient = models.ForeignKey(Patient)

    def __str__(self):
        return self.patient.first_name + "'s Schedule"


class Vaccine(models.Model):
    schedule = models.ForeignKey(Schedule)
    name = models.CharField(max_length=50)
    description = models.TextField()

    def __str__(self):
        return self.name


class Dose(models.Model):
    vaccine = models.ForeignKey(Vaccine)
    name = models.CharField(max_length=60)
    given = models.BooleanField(default=False)
    date = models.DateField(blank=True, null=True)

    def __str__(self):
        return f'{self.vaccine.schedule.patient.first_name} {self.vaccine.schedule.patient.last_name} - {self.name}'

schedule/views.py
# from string import split
from datetime import datetime

from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render


@login_required
def index(request):
    user = request.user
    families = user.patientfamily_set.all()
    return render(request, 'schedule/index.html', {'request': request, 'families': families, })


@login_required
def chart(request, family_id, member_id):
    user = request.user
    family = user.patientfamily_set.filter(pk=family_id)[0]
    member = family.patient_set.filter(pk=member_id)[0]
    schedule = member.schedule_set.all()
    doses = None
    if schedule:
        schedule = schedule[0]
        vaccines = schedule.vaccine_set.all()
        doses = []
        for vaccine in vaccines:
            doses.append(vaccine.dose_set.all())
    return render(request, 'schedule/chart.html',
                  {'request': request, 'family': family, 'member': member, 'doses': doses})


@login_required
def update_schedule(request, family_id, member_id):
    user = request.user
    family = user.patientfamily_set.filter(pk=family_id)[0]
    member = family.patient_set.filter(pk=member_id)[0]
    schedule = member.schedule_set.all()[0]
    vaccines = schedule.vaccine_set.all()
    doses = []
    for vaccine in vaccines:
        doses.append(vaccine.dose_set.all())
    values = []
    for value in request.POST:
        for dose_list in doses:
            for dose in dose_list:
                if dose.name in value:
                    if request.POST[value] != '':
                        dose.given = True
                        date = request.POST[value]
                        formatted_date = datetime.strptime(date, '%m/%d/%Y').strftime('%Y-%m-%d')
                        dose.date = formatted_date
                        dose.save()
                        return HttpResponseRedirect(reverse('schedule:chart', args=(family.id, member.id,)))

    return render(request, 'schedule/update.html', {'values': values})


@login_required
def new_family_view(request):
    return render(request, 'schedule/new_family.html', None)


@login_required
def add_family(request):
    user = request.user
    family = user.patientfamily_set.create(last_name=request.POST['last_name'])
    family.save()
    return HttpResponseRedirect(reverse('schedule:family', args=(family.id,)))


@login_required
def family_view(request, family_id):
    user = request.user
    family = user.patientfamily_set.filter(id=family_id)[0]
    members = family.patient_set.all()
    return render(request, 'schedule/family.html', {'family': family, 'members': members, })


# Helper function used by new_schedule()
def create_doses(vaccine, number):
    for i in range(1, number + 1):
        dose = vaccine.dose_set.create(name=vaccine.name + "_" + str(i))
        dose.save()


def new_schedule(member):
    # Create schedule
    schedule = member.schedule_set.create()
    schedule.save()

    # Hepatitis B Vaccine
    hepatitis_b = schedule.vaccine_set.create(name="hepatitis_b", description="Hepatitis B")
    hepatitis_b.save()
    create_doses(hepatitis_b, 5)

    # DTAP Vaccine
    dtap = schedule.vaccine_set.create(name="dtap", description="Diptheria, Tetanus, Pertusis")
    dtap.save()
    create_doses(dtap, 6)

    # H. Influenzae Vaccine
    influenzae = schedule.vaccine_set.create(name="influenzae", description="H. influenzae type b")
    influenzae.save()
    create_doses(influenzae, 4)

    # Pollo Vaccine
    pollo = schedule.vaccine_set.create(name="pollo", description="Inactivated Pollo")
    pollo.save()
    create_doses(pollo, 4)

    # Pneumococcal Vaccine
    pneumococcal = schedule.vaccine_set.create(name='pneumococcal', description="Pneumococcal Conjugate")
    pneumococcal.save()
    create_doses(pneumococcal, 4)

    # MMR Vaccine
    mmr = schedule.vaccine_set.create(name='mmr', description='Measles, Mumps, Rubella')
    mmr.save()
    create_doses(mmr, 3)

    # Varicella Vaccine
    varicella = schedule.vaccine_set.create(name='varicella', description="Varicella (Chickenpox)")
    varicella.save()
    create_doses(varicella, 2)

    # Hepatitis A Vaccine
    hepatitis_a = schedule.vaccine_set.create(name='hepatitis_a', description="Hepatitis A")
    hepatitis_a.save()
    create_doses(hepatitis_a, 1)


@login_required
def add_member(request, family_id):
    user = request.user
    family = user.patientfamily_set.filter(id=family_id)[0]
    member = family.patient_set.create(last_name=request.POST['last_name'], first_name=request.POST['first_name'])
    member.save()
    new_schedule(member)
    return HttpResponseRedirect(reverse('schedule:family', args=(family_id,)))

schedule/templates/schedule/family.html
{% extends 'main/base.html' %}

{% block title %}Family{% endblock %}
{% block schedule_class %}active{% endblock %}
{% block content %}
    <h1>{{ family.last_name }} family</h1>
    <h3>Current family members:</h3>
    {% if members %}
        {% for member in members %}
            <p>{{ member.first_name }} {{ member.last_name }} - <a
                    href="{% url 'schedule:chart' family.id member.id %}"> View {{ member.first_name }}'s immunization
                chart</a></p>
        {% endfor %}
    {% else %}
        <p>No family members to display yet, get started by adding a family member using the form below!</p>
    {% endif %}
    <h3>Add a family member:</h3>

    <form class="form-group" action="{% url 'schedule:add_member' family.id %}" method="post">
        {% csrf_token %}
        <input type="text" placeholder="First name of family member" class="form-control" name="first_name"/>
        <br/>
        <input type="text" placeholder="Last name of family member" class="form-control" name="last_name"/>
        <br/>
        <input type="submit" value="Add family member" class="form-control"/>
    </form>
{% endblock %}

schedule/templates/schedule/index.html
{% extends 'main/base.html' %}

{% block title %}Schedules{% endblock %}
{% block schedule_class %}active{% endblock %}
{% block content %}
    <h1>Immunization Schedules</h1>
    <h3>Here you can view and create immunization schedule charts for your family or for patients. </h3>
    <br/>
    <h3 class="page-header">Added Families</h3>
    {% if families %}
        {% for family in families %}
            <h5><a href="{% url 'schedule:family' family.id %}">- {{ family.last_name }}</a></h5>
        {% endfor %}
        <h5><a href="{% url 'schedule:new_family' %}">Add a new family</a></h5>
    {% else %}
        <h4>Get started <a href="{% url 'schedule:new_family' %}">here</a> by adding a new family along with each family
            member that you
            want to track immunizations for.
        </h4>
    {% endif %}

    <br/>
    <br/>
{% endblock %}

schedule/templates/schedule/new_family.html
{% extends 'main/base.html' %}

{% block title %}New Family{% endblock %}
{% block schedule_class %}active{% endblock %}
{% block content %}
    <h1>Add a new family</h1>
    <form action="{% url 'schedule:add_family' %}" method="post" class="form-group">
        {% csrf_token %}
        <input name="last_name" type="text" placeholder="Last name (Can be changed for individual family members)"
               class="form-control"/>
        <br/>
        <input type="submit" value="Add family" class="form-control"/>
    </form>
{% endblock %}

schedule/templates/schedule/update.html
{% extends 'main/base.html' %}


{% block content %}
    {{ values }}
{% endblock %}